# Generated by Django 4.2.13 on 2024-06-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('Sales Advisor', 'Sales Advisor'), ('Manager', 'Manager')], default='Manager', max_length=50),
        ),
    ]
